"""Add year_built field to Property model

Revision ID: f5c3f3da5ac1
Revises: fbc7d5ebd8c5
Create Date: 2025-06-12 22:27:35.342387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c3f3da5ac1'
down_revision = 'fbc7d5ebd8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_built', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_properties_year_built'), ['year_built'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_year_built'))
        batch_op.drop_column('year_built')

    # ### end Alembic commands ###
